[project]
name = "app-tickets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet>=0.28.3",
    "opencv-python>=4.12.0.88",
    "playwright>=1.55.0",
]
